name: web_sdk_tests

# Keep the SDK version range in sync with lib/web_ui/pubspec.yaml
environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  args: 2.3.1
  path: 1.8.2

dev_dependencies:
  analyzer: 5.7.1
  test: 1.22.1
  pub_semver: 2.1.3
