gcp_credentials: ENCRYPTED[a4b6c1cb428a657573b775d39dd8006beed3013d01ca3d1a3972bdc2bd39bb937dd91ea3d98eeb9ce55e4bd303d045d3]

# LINUX
task:
  gke_container:
    dockerfile: "ci/docker/build/Dockerfile"
    builder_image_name: docker-builder # gce vm image
    builder_image_project: flutter-cirrus
    cluster_name: build-32-cluster
    zone: us-central1-a
    namespace: default
    cpu: 30 # can't use all 30-cores; system pods needs cores too
    memory: 100Gb # similarly, can't use all 100Gb memory
  env:
    CIRRUS_DOCKER_CONTEXT: "ci/docker/build"
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    ENGINE_PATH: "/tmp/clean_engine"
    DEPOT_TOOLS: "/tmp/depot_tools"
    FLUTTER_ENGINE: "/tmp/clean_engine/src"
    FRAMEWORK_PATH: "/tmp/master_framework"
    PATH: "$FLUTTER_ENGINE/third_party/dart/tools/sdks/dart-sdk/bin:$DEPOT_TOOLS:$PATH"
    USE_ANDROID: "False"
  setup_script: |
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git $DEPOT_TOOLS
    mkdir -p $ENGINE_PATH/src
    echo 'solutions = [{"managed": False,"name": "src/flutter","url": "git@github.com:flutter/engine.git","deps_file": "DEPS", "custom_vars": {"download_android_deps" : ' $USE_ANDROID ', "download_windows_deps" : False,},},]' > $ENGINE_PATH/.gclient
    cd $ENGINE_PATH/src
    rm -rf flutter
    rm -rf out
    mv $CIRRUS_WORKING_DIR flutter
    gclient sync
  matrix:
    # TODO(fujino): remove this once ci/licenses.sh is run on LUCI
    - name: licenses_check
      build_script: |
        cd $ENGINE_PATH/src/flutter
        ./ci/licenses.sh
